# Generated by Django 3.2.6 on 2021-08-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehiclesDetail',
            fields=[
                ('v_id', models.AutoField(primary_key=True, serialize=False)),
                ('engine_status', models.CharField(max_length=200)),
                ('fuel_level', models.CharField(max_length=200)),
                ('tampreture', models.CharField(max_length=200)),
                ('average_speed', models.CharField(max_length=200)),
                ('speed', models.CharField(max_length=200)),
            ],
        ),
    ]
